services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means
    # fetching services directly from the container via $container->get() won't work.
    # The best practice is to be explicit about your dependencies anyway.

  BarthyKoeln\ImageUploadBundle\DependencyInjection\ImageUploadConfig:
    public: true

  BarthyKoeln\ImageUploadBundle\Twig\ImageFilterExtension:
    public: true

  BarthyKoeln\ImageUploadBundle\EventListener\ImageListener:
    tags:
      - { name: doctrine.event_listener, event: onFlush }

  BarthyKoeln\ImageUploadBundle\Validator\FileSizeConstraintValidator: ~

  BarthyKoeln\ImageUploadBundle\Validator\FileTitleConstraintValidator: ~

  BarthyKoeln\ImageUploadBundle\Form\ImageUploadType:
    public: true
    tags:
      - { name: form.type }

  BarthyKoeln\ImageUploadBundle\Form\SortableImageUploadType:
    public: true
    tags:
      - { name: form.type }

  BarthyKoeln\ImageUploadBundle\Form\ImageCollectionType:
    public: true
    tags:
      - { name: form.type }

  BarthyKoeln\ImageUploadBundle\Form\SortableImageCollectionType:
    public: true
    tags:
      - { name: form.type }
